# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6.10p210'
    addToPath: false

# Add Ruby to the PATH manually with the desired path.
- script: |
    echo "##vso[task.setvariable variable=PATH]$(PATH):/usr/local/opt/ruby/bin/ruby"
  displayName: 'Add Ruby to PATH'

# Verify the Ruby version
- script: |
    ruby -v
  displayName: 'Check Ruby Version'

- script: |
    echo "Ruby version $(ruby -v)"
    echo "Ruby versions $(rbenv versions)"
    echo "Gem version $(gem -v)"
    echo "Xcode path $(xcode-select --print-path)"
    echo "Xcode version $(xcodebuild -version)"
    echo "Ruby version $(ruby -v)"
    echo "Node versino $(node -v)"
    echo "Which xpretty $(which xcpretty)"
    echo "xcpretty $(xcpretty -v)"
    which /usr/local/opt/ruby/bin/ruby
    /usr/local/opt/ruby/bin/ruby -v
    which ruby
    ruby -v
    which xcpretty 
    xcpretty -v

    npm install
    npm run build
    npm test
  displayName: 'npm install and build'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
